### ISSUE TITLE
[Feature] filter by multiple tags

### ISSUE THREAD

**Issue by SergioMSCosta** [tonehunt-org/tonehunt#170]
I would like to be able to filter by multiple tags. The way I see it, every time we clicked a tag, it would add it to the poll of tags already filtered by. We could then hover a tag (which would be displayed on top) and remove it from the filter.

**Comment by prodz18** [comment]
You can actually search by multiple tags in the url. For example `?tags=rock,metal,clean`
We are thinking of ways of improving the whole tag system (from selecting them when uploading, better filtering, etc).

**Comment by LiamClark** [comment]
I actually wanted this feature too, and am having a shot at implementing it right now.
I started out just highlighting the active tags in the sidebar to get started. If that is a welcome contribution let me know!
I'd like to impelement the additional filtering with multiple tags now.
I'd love to hear if you guys have any design input for this in how the feature should work!

**Comment by scottcorgan** [comment]
> I actually wanted this feature too, and am having a shot at implementing it right now. I started out just highlighting the active tags in the sidebar to get started. If that is a welcome contribution let me know! I'd like to impelement the additional filtering with multiple tags now. I'd love to hear if you guys have any design input for this in how the feature should work!

@LiamClark to make sure what you're doing doesn't have merge conflicts, make sure you're working off of the `feature/new-layout` branch. We have a fairly large refactor and layout update there. We have yet to work on the tags portion of it, but I'm excited to see what you do. 

I'd say, make it work, then we can do a design pass on it.

**Comment by prodz18** [comment]
We added a new filtering system in the next release. Closing.
