### ISSUE TITLE
Login with password-manager

### ISSUE THREAD

**Issue by ulibike** [tonehunt-org/tonehunt#184]
When using KeePassXC to login, the webpage doesn't give me the chance to fill out the password, the login-popup closes before the tool pasting the password.

![passwdmanager](https://user-images.githubusercontent.com/80952239/231123243-6f758b14-fc56-4146-b06b-7b8b147ddb8e.gif)

**Comment by ulibike** [comment]
Yes, still the same behavior as in the gif.

**Comment by jeffrutland** [comment]
@ulibike - I've tested this with both LastPass and NordPass, in both Safari and Chrome and I don't see this behavior.  What browser are you using here

**Comment by ulibike** [comment]
Yes, most likely it's a keepassXC (or the Firefox add-on) problem, then. It's fine for me. I can also log in manually.
