### ISSUE TITLE
Blue focus ring stays on central buttons after click

### ISSUE THREAD

**Issue by caleb-shelton** [tonehunt-org/tonehunt#213]
On Windows/Chrome...

Only on some buttons located towards the centre of the page such as: "Newest", "Popular", "Following", Star-rating, Download buttons, a blue focus ring stays on the button after click.

It looks like:

![tonehunt_pr2](https://user-images.githubusercontent.com/5530323/232625931-2c855e17-bb88-405c-b54a-702ef702ddcd.png)

I think it would look better to remove this, but if possible keep it so it appears when using tab to cycle through the options for accessibility purposes. The same as for example, Github's buttons, they are blue when pressing tab, but they don't stay blue after click.

**Comment by prodz18** [comment]
Fixed on next update.
Closing.
