### ISSUE TITLE
Popular normalized by recency

### ISSUE THREAD

**Issue by mourner** [tonehunt-org/tonehunt#236]
Currently, the [Popular tab](https://tonehunt.org/?sortBy=popular) has a bias towards older models, because they've stayed on the site for longer. It would be cool to have another sorting measure that normalizes popularity by the time they've been up — so models that would have the highest ratio of downloads or stars per day would be at the top. Maybe call it "Trending" or "Hot" like on Reddit?

**Comment by prodz18** [comment]
Hi! We are actually going to release an update really soon that will include some of the things that you mentioned. Stay tune for that. Thanks for the feedback!

**Comment by mourner** [comment]
Awesome, looking forward to it — thank you!

**Comment by prodz18** [comment]
Fixed on next update.
Closing.
