### ISSUE TITLE
Search doesn't work properly for tags

### ISSUE THREAD

**Issue by mourner** [tonehunt-org/tonehunt#237]
If I search for a particular tag, e.g. `#bass`, Tonehunt includes results that have no such tag but instead simply contain the word "bass" in the description, making it difficult to narrow down models:

<img width="762" alt="image" src="https://user-images.githubusercontent.com/25395/235785366-1d6f7ac2-323d-4a8c-9d3d-9bbd4860822c.png">

**Comment by scottcorgan** [comment]
Thanks! Ya, it's a known issue we will work to address!.

**Comment by mourner** [comment]
@scottcorgan Looks like browsing by tags got broken after the redesign as well — e.g. https://tonehunt.org/all?tags=bass, it shows all models (not just `#bass`).

**Comment by azzzy** [comment]
@scottcorgan, I've opened a PR which adds the possibility to filter by multiple tags.

I am not sure if conjunction or disjunction will be more useful, currently the model is shown if it matches at least one of the tags.
I tested it only with the seed data provided with the project, it would be nice to test it with a larger number of DB records.

**Comment by prodz18** [comment]
Fixed.
