### ISSUE TITLE
Ability to use IRs and NAM on website

### ISSUE THREAD

**Issue by RustoMCSpit** [tonehunt-org/tonehunt#241]
ToneHunt should ask the user to listen to their mic / audio interface so that you can play with stuff on the website without downloading it

**Comment by RustoMCSpit** [comment]
similar to the closed .wav idea

**Comment by prodz18** [comment]
We now have integration with NAM Online Player. Closing.

**Comment by RustoMCSpit** [comment]
> We now have integration with NAM Online Player. Closing.

AWESOME!?!?
