### ISSUE TITLE
Have the amount of columns be responsive to the size of the screen and have the amount of rows be adjustable

### ISSUE THREAD

**Issue by RustoMCSpit** [tonehunt-org/tonehunt#246]
There's little reason to have one set of columns on my 30 inch wide monitor when the website could easily do three columns. Add a feature that allows me to choose the amount of columns and how many rows each column should have e.g. Show 50 per row, Show 100 per row, etc..

**Comment by RustoMCSpit** [comment]
Maybe have the amounts be dynamic

**Comment by prodz18** [comment]
We have some improvements across the whole website regarding layout and responsiveness. We are also introducing Grid View and List View in the new Models page. All this is coming in the next release. Closing.
