### ISSUE TITLE
BUG: If I click the explore all amps button at the top, the pill on the right still says "All"

### ISSUE THREAD

**Issue by RustoMCSpit** [tonehunt-org/tonehunt#248]
https://tonehunt.org/?filter=amp

https://tonehunt.org/?page=1&filter=amp&sortBy=newest&sortDirection=desc

Weird to have two separets URLS too

**Comment by prodz18** [comment]
Fixed on next update.
Closing.

**Comment by RustoMCSpit** [comment]
> Fixed on next update. Closing.

when will that be roughly

**Comment by prodz18** [comment]
Currently testing. Should be up in a couple of hours.

**Comment by RustoMCSpit** [comment]
> Currently testing. Should be up in a couple of hours.

could uou tag all the github ideas?

**Comment by RustoMCSpit** [comment]
> Currently testing. Should be up in a couple of hours.

also awrdome so haopy to hear thank you so much
